# Generated by Django 4.2.5 on 2023-11-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
