# Generated by Django 4.2.6 on 2023-11-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_id', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
