# Generated by Django 4.2.5 on 2023-11-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist', verbose_name='Artist Album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Artist Name'),
        ),
    ]
