# Generated by Django 4.2.5 on 2023-11-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_album_artist_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Album Name'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist', verbose_name='Artist Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album', verbose_name='Song Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='songName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Song Name'),
        ),
    ]
