# Generated by Django 4.2.5 on 2023-11-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_album_albumname_alter_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlistName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Playlist Name'),
        ),
    ]
